"""Repository grounding — retrieve relevant repo content for each question.

Two retrieval sources, both cheap and serverless-friendly:

1. **MkDocs search index** (``search_index.json``) — built from the full
   docs site (docs/, tutorials/, poc-agenda/). Fetched once per instance
   from the published site and cached in memory.

2. **Code manifest** (``code_manifest.json``) — generated by
   ``build_code_manifest.py`` at deploy time; indexes notebooks, data
   generators, and Bicep modules with titles/summaries/keywords.

Both use the same lightweight term-scoring ranker (no embeddings, no
external service) so the Function stays on the Consumption plan with no
extra Azure resources. Retrieved chunks are injected into the system
context so Mode 1 answers cite *actual* repo content instead of the
model's parametric memory.

Failure model: if either source is unavailable, retrieval returns an
empty list and the Copilot answers as before (system prompt + optional
MS Learn fallback). Grounding is additive, never blocking.
"""

from __future__ import annotations

import json
import logging
import os
import re
import threading
import time
from pathlib import Path

import httpx

# ── Configuration ───────────────────────────────────────────────
DOCS_SITE_URL = os.environ.get(
    "DOCS_SITE_URL",
    "https://fgarofalo56.github.io/Suppercharge_Microsoft_Fabric",
).rstrip("/")
SEARCH_INDEX_URL = f"{DOCS_SITE_URL}/search/search_index.json"
MANIFEST_PATH = Path(__file__).resolve().parent / "code_manifest.json"

HTTP_TIMEOUT = 20.0
INDEX_TTL_SECONDS = 6 * 60 * 60  # re-fetch the search index every 6h
MAX_CHUNKS_PER_SOURCE = 4
MAX_CHUNK_CHARS = 700
MAX_CONTEXT_CHARS = 6000

# ── In-memory caches (per instance; cold-start safe) ────────────
_index_cache: dict = {"data": None, "fetched_at": 0.0}
_manifest_cache: dict = {"data": None}
_lock = threading.Lock()


# ── Loading ─────────────────────────────────────────────────────
def _load_search_index() -> list[dict]:
    """Fetch + cache the MkDocs search index. Returns [] on failure."""
    now = time.time()
    with _lock:
        if (
            _index_cache["data"] is not None
            and (now - _index_cache["fetched_at"]) < INDEX_TTL_SECONDS
        ):
            return _index_cache["data"]

    try:
        with httpx.Client(timeout=HTTP_TIMEOUT) as client:
            r = client.get(SEARCH_INDEX_URL)
        if r.status_code != 200:
            logging.warning("repo_grounding: search index HTTP %s", r.status_code)
            return _index_cache["data"] or []
        data = r.json()
        docs = data.get("docs", []) if isinstance(data, dict) else []
        with _lock:
            _index_cache["data"] = docs
            _index_cache["fetched_at"] = now
        logging.info("repo_grounding: loaded search index (%d docs)", len(docs))
        return docs
    except Exception as e:
        logging.warning("repo_grounding: search index fetch failed: %s", e)
        return _index_cache["data"] or []


def _load_manifest() -> list[dict]:
    """Load the bundled code manifest. Returns [] if missing."""
    with _lock:
        if _manifest_cache["data"] is not None:
            return _manifest_cache["data"]
    try:
        raw = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        entries = raw.get("entries", []) if isinstance(raw, dict) else []
    except Exception as e:
        logging.warning("repo_grounding: manifest load failed: %s", e)
        entries = []
    with _lock:
        _manifest_cache["data"] = entries
    logging.info("repo_grounding: loaded code manifest (%d entries)", len(entries))
    return entries


# ── Ranking ─────────────────────────────────────────────────────
_WORD_RE = re.compile(r"[a-z0-9_]{2,}")

_STOP = {
    "the",
    "a",
    "an",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "to",
    "of",
    "in",
    "on",
    "for",
    "and",
    "or",
    "but",
    "with",
    "from",
    "by",
    "at",
    "as",
    "it",
    "this",
    "that",
    "these",
    "those",
    "i",
    "you",
    "we",
    "they",
    "he",
    "she",
    "do",
    "does",
    "did",
    "how",
    "what",
    "where",
    "when",
    "who",
    "why",
    "which",
    "can",
    "could",
    "should",
    "would",
    "me",
    "my",
    "your",
    "their",
    "our",
    "its",
    "if",
    "then",
    "than",
    "so",
    "such",
    "not",
    "no",
    "yes",
    "all",
    "any",
    "some",
    "there",
    "here",
    "about",
    "into",
    "over",
    "under",
    "between",
    "use",
    "using",
    "used",
    "make",
    "get",
    "set",
    "up",
    "out",
}


def _terms(query: str) -> list[str]:
    return [t for t in _WORD_RE.findall(query.lower()) if t not in _STOP]


def _score(
    terms: list[str], title: str, text: str, extra: list[str] | None = None
) -> float:
    title_l = title.lower()
    text_l = text.lower()
    extra_l = " ".join(extra or []).lower()
    score = 0.0
    for term in terms:
        if term in title_l:
            score += 10.0
        if re.search(rf"\b{re.escape(term)}\b", title_l):
            score += 5.0
        if term in extra_l:
            score += 4.0
        # Cap body hits so long docs don't dominate
        score += min(text_l.count(term), 5)
    return score


_TAG_RE = re.compile(r"<[^>]+>")


def _strip_html(text: str) -> str:
    """MkDocs index text contains raw HTML — strip tags, collapse whitespace."""
    return re.sub(r"\s{2,}", " ", _TAG_RE.sub(" ", text)).strip()


def _snippet(text: str, terms: list[str], width: int = MAX_CHUNK_CHARS) -> str:
    clean = _strip_html(text)
    clean_l = clean.lower()
    best = -1
    for t in terms:
        idx = clean_l.find(t)
        if idx != -1 and (best == -1 or idx < best):
            best = idx
    if best == -1:
        return clean[:width].strip()
    start = max(0, best - 120)
    end = min(len(clean), best + width - 120)
    prefix = "…" if start > 0 else ""
    suffix = "…" if end < len(clean) else ""
    return prefix + clean[start:end].strip() + suffix


# ── Public API ──────────────────────────────────────────────────
def retrieve(query: str, max_chunks: int = MAX_CHUNKS_PER_SOURCE) -> list[dict]:
    """Return up to ``max_chunks`` grounding chunks for ``query``.

    Each chunk: {"source": "docs"|"code", "title", "location"|"path",
                 "url", "text", "score"}. Sorted by score desc.
    Never raises — returns [] when nothing matches or sources unavailable.
    """
    terms = _terms(query)
    if not terms:
        return []

    chunks: list[dict] = []

    # ── Docs (MkDocs search index) ──────────────────────────────
    for doc in _load_search_index():
        title = doc.get("title") or ""
        text = doc.get("text") or ""
        location = doc.get("location") or ""
        if not location or not text:
            continue
        s = _score(terms, title, text)
        if s > 0:
            chunks.append(
                {
                    "source": "docs",
                    "title": title or location,
                    "location": location,
                    "url": f"{DOCS_SITE_URL}/{location}",
                    "text": _snippet(text, terms),
                    "score": s,
                }
            )

    # ── Code manifest (notebooks / generators / bicep) ─────────
    for entry in _load_manifest():
        s = _score(
            terms,
            entry.get("title", ""),
            entry.get("summary", ""),
            extra=[*entry.get("keywords", []), entry.get("path", "")],
        )
        if s > 0:
            chunks.append(
                {
                    "source": "code",
                    "title": f"{entry.get('title', '')} ({entry.get('type', 'code')})",
                    "path": entry.get("path", ""),
                    "url": entry.get("path", ""),
                    "text": entry.get("summary", "")[:MAX_CHUNK_CHARS],
                    "score": s,
                }
            )

    chunks.sort(key=lambda c: c["score"], reverse=True)

    # Dedupe docs hits by page (keep highest-scoring anchor per page)
    seen_pages: set[str] = set()
    deduped: list[dict] = []
    for c in chunks:
        if c["source"] == "docs":
            page = c["location"].split("#")[0]
            if page in seen_pages:
                continue
            seen_pages.add(page)
        deduped.append(c)
        if len(deduped) >= max_chunks * 2:
            break

    # Keep a mix: up to max_chunks docs + up to max_chunks code
    docs_hits = [c for c in deduped if c["source"] == "docs"][:max_chunks]
    code_hits = [c for c in deduped if c["source"] == "code"][:max_chunks]
    return docs_hits + code_hits


def format_grounding_context(chunks: list[dict]) -> str:
    """Render retrieved chunks as a system-message context block.

    Bounded to MAX_CONTEXT_CHARS so the prompt budget stays predictable.
    """
    if not chunks:
        return ""
    lines = [
        "## Retrieved repository content (ground this answer in THESE sources)",
        "Cite these paths/URLs in your answer. If none of these are relevant, say so and fall back to your other modes.",
        "",
    ]
    total = 0
    for i, c in enumerate(chunks, 1):
        if c["source"] == "docs":
            header = f"[{i}] DOCS: {c['title']} — {c['url']}"
        else:
            header = f"[{i}] CODE: {c['title']} — `{c.get('path', '')}`"
        block = f"{header}\n{c['text']}\n"
        if total + len(block) > MAX_CONTEXT_CHARS:
            break
        lines.append(block)
        total += len(block)
    return "\n".join(lines)


# Diagnostic helper — python repo_grounding.py "your question"
if __name__ == "__main__":
    import sys

    q = " ".join(sys.argv[1:]) or "bronze NOAA ingestion notebook"
    hits = retrieve(q)

    def _safe(s: str) -> str:
        return s.encode("ascii", errors="replace").decode("ascii")

    print(f"{len(hits)} chunks for {q!r}:\n")
    for h in hits:
        print(_safe(f"  [{h['source']}] {h['title']} (score {h['score']:.1f})"))
        print(_safe(f"    {h.get('url') or h.get('path')}"))
    print("\n--- formatted context ---")
    print(_safe(format_grounding_context(hits)[:1500]))
